### ISSUE TITLE
setup laptop with Install.sh 

### ISSUE THREAD

**Issue by mohammad-javed** [DemisR/mac-devops-setup#1]
I am using macOS Mojave version 10.14.3 I am facing below issue.

TASK [setup_homebrew : Ensure Homebrew parent directory has correct permissions.] ************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "gid": 0, "group": "wheel", "mode": "0755", "msg": "chgrp failed", "owner": "root", "path": "/usr/local", "size": 480, "state": "directory", "uid": 0}

I tried with all users root, sudo, su.

could please help me to setup

**Comment by DemisR** [comment]
Should be corrected with these changes.
