### ISSUE TITLE
Error when running the ansible-playbook

### ISSUE THREAD

**Issue by Alitejawi** [DemisR/mac-devops-setup#3]
When running the ansible playbook, the following error presents: 

----
test@tests-MacBook-Pro mac-devops-setup % ansible-playbook setup-my-mac.yml -i inventory -K
BECOME password: 
ERROR! conflicting action statements: command, chdir

The error appears to be in '/Users/test/mac-devops-setup/roles/setup_homebrew/tasks/main.yml': line 114, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Install from Brewfile.
  ^ here
----

**Comment by DemisR** [comment]
I've fixed the command arguments (change in recents releases of ansible module).
Should be fixed now. 
Please let me know if still not working.
